version: '3.8'

services:
  
  # -----------------------------------------------
  # 1. ORQUESTADOR: NGINX
  # -----------------------------------------------
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy-auth
    ports:
      - "80:80" 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth-mongo-service
    networks:
      - app-network
    restart: always

  # -----------------------------------------------
  # 2. MICROSERVICIO: AUTH-MONGO-SERVICE
  # -----------------------------------------------
  auth-mongo-service:
    build:
      context: ./auth-mongo-service/
      dockerfile: Dockerfile
    container_name: auth-mongo-service-container
    ports:
      - "3000:3000" 
    environment:
      # Conexi√≥n al servicio de DB usando el nombre del servicio en Docker: 'db-auth-mongo'
      MONGO_URI: mongodb://db-auth-mongo:27017/servicio_usuarios_test 
      JWT_SECRET: EstaEsUnaClaveMuySeguraDeAlMenos32Bytes!
    depends_on:
      db-auth-mongo:
        condition: service_started
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # -----------------------------------------------
  # 3. BASE DE DATOS: DB-AUTH-MONGO
  # -----------------------------------------------
  db-auth-mongo:
    image: mongo:latest
    container_name: mongo_auth_users
    # Mapeo de puerto para acceder con MongoDB Compass (localhost:27019)
    ports:
      - "27017:27017" 
    volumes:
      - auth_mongo_data:/data/db 
    networks:
      - app-network
    restart: always


networks:
  app-network:
    driver: bridge

volumes:
  auth_mongo_data: